#!/usr/bin/env ruby

require "pathname"

if ENV["VOP_DEV_MODE"]
  sibling_lib_dir = Pathname.new(File.join(File.dirname(__FILE__), "..", "lib")).realpath
  if File.exists? sibling_lib_dir
    #puts "adding local lib path #{sibling_lib_dir}"
    $: << sibling_lib_dir
  end
end

require "vop"

vop = Vop.setup
Vop::Shell.run(vop)
