#!/usr/bin/env ruby

require 'pathname'

$: << File.join(Pathname.new(File.join(File.dirname(__FILE__), '..')).realpath, 'lib')

require 'vop/shell'
require 'docopt'
require 'pp'

begin
  shell = Vop::Shell::setup()
  last_response = if shell.options["--execute"]
    shell.execute(shell.options["--execute"])
  else
    shell.run_cli
  end

  exit_status = last_response && last_response.status == "ok" ? 0 : 1
  exit exit_status
rescue => detail
  if detail.is_a? Docopt::Exit
    puts detail.message
  else
    $stderr.puts "error : #{detail.message}\n#{detail.backtrace[0..9].join("\n")}"
    exit 42
  end
end
